{
 "title": "Astro Deployment Overview",
 "tags": [ "airflow" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "label_values(namespace)" } },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$deployment\"}, cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Selected Deployment: ${deployment} / Cluster: $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "description": "Average heartbeat of your scheduler. If there are multiple schedulers the number of combined heartbeat could increase.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(airflow_scheduler_heartbeat_total{namespace=\"$deployment\"}[5m])) * 60",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "title": "Scheduler Health",
   "type": "stat",
   "description": "Indication of whether the scheduler is up and running its loop. An value of \"Unknown\" means that the airflow image is running an older version.",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat_total{namespace=~\"$deployment\", type=\"counter\"}[5m])",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "title": "API Server Health",
   "type": "stat",
   "description": "Keeps track of health in terms of its pod readiness",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (namespace, container) (kube_pod_status_ready{ namespace=\"$deployment\", pod=~\".*apiserver.*\"})) == bool 1 or on () vector(0)",
     "legendFormat": "API Server"
    }
   ]
  },
  { "title": "DAG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total DAG Runs",
   "type": "stat",
   "description": "Total DAG runs within the time range",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(floor(increase(airflow_dagrun_duration_count{namespace=\"$deployment\"}[$__range])))",
     "legendFormat": "Success"
    },
    {
     "expr": "max(floor(increase(airflow_dagrun_failed_count{namespace=\"$deployment\"}[$__range])))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "DAG Import Errors",
   "type": "timeseries",
   "description": "Errors when importing DAG resulted in error",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{namespace=\"$deployment\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "DAG Run Trend",
   "type": "timeseries",
   "description": "Tracks number of successful and failed dag runs within the time range of monitor",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(round(increase(airflow_dagrun_duration_count{namespace=\"$deployment\"}[1h]))) or on ()vector(0)",
     "legendFormat": "Success per/hour"
    },
    {
     "expr": "max(round(increase(airflow_dagrun_failed_count{namespace=\"$deployment\"}[1h]))) or on ()vector(0)",
     "legendFormat": "Failed per/hour"
    }
   ]
  },
  {
   "title": "Peak Hourly P90 DAG Run Schedule Delay",
   "type": "timeseries",
   "description": "Delay between the scheduled and actual DAG run",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(max_over_time(airflow_dagrun_schedule_delay{namespace=\"$deployment\", quantile=\"0.9\"}[1h])) or on () vector(0)",
     "legendFormat": "Schedule Delay"
    }
   ]
  },
  {
   "title": "DAG processing parse time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(airflow_dag_processing_total_parse_time{namespace=\"$deployment\"}) or on () vector(0)",
     "legendFormat": "Parse Time"
    }
   ]
  },
  {
   "title": "Peak Hourly P90 Successful Dag Run duration per hour",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(max_over_time(airflow_dagrun_duration{namespace=\"$deployment\", quantile=\"0.9\"}[1h])) or on () vector(0)",
     "legendFormat": "p90 success response time"
    }
   ]
  },
  {
   "title": "DAG Bag Size",
   "type": "stat",
   "description": "Size of DAG Bag",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(airflow_dagbag_size{namespace=\"$deployment\"})",
     "legendFormat": "DagBag Size"
    }
   ]
  },
  { "title": "TASK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total TASK runs",
   "type": "stat",
   "description": "Total number of running tasks within the time range",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(round(increase(airflow_ti_successes_total{namespace=\"$deployment\"}[$__range])))",
     "legendFormat": "Success"
    },
    {
     "expr": "max(round(increase(airflow_ti_failures_total{namespace=\"$deployment\"}[$__range])))",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(round(increase(airflow_zombies_killed{namespace=\"$deployment\"}[$__range])))",
     "legendFormat": "Zombies Killed"
    }
   ]
  },
  {
   "title": "TASK Status",
   "type": "timeseries",
   "description": "Total number of running tasks within the time range",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(airflow_executor_running_tasks{namespace=\"$deployment\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max(airflow_executor_queued_tasks{namespace=\"$deployment\"})",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "TASK Run Trend",
   "type": "timeseries",
   "description": "Total number of running tasks within the time range",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(round(increase(airflow_ti_successes_total{namespace=\"$deployment\"}[1h])))",
     "legendFormat": "Success per/hour"
    },
    {
     "expr": "max(round(increase(airflow_ti_failures_total{namespace=\"$deployment\"}[1h])))",
     "legendFormat": "Failed per/hour"
    }
   ]
  },
  {
   "title": "Tasks Starving",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(airflow_scheduler_tasks_starving{namespace=\"$deployment\"})",
     "legendFormat": "Tasks Starving"
    }
   ]
  },
  {
   "title": "Peak P90 task duration per hour ( per DAG )",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(airflow_task_duration{namespace=\"$deployment\", quantile=\"0.9\"}[1h]) or on() vector(0)) by (dag_id) > 0",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Zombie Tasks Killed over time",
   "type": "timeseries",
   "description": "Zombies are the tasks which is stated to be RUNNING, but its latest heartbeat was older than the zombie heartbeat threshold, and thus killed by scheduler.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(airflow_zombies_killed_total{namespace=\"$deployment\"})",
     "legendFormat": "Killed Zombies"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Scheduler Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (container_memory_working_set_bytes{namespace=\"$deployment\", container=\"scheduler\"}) or on ()vector(0)",
     "legendFormat": "Schedulers"
    }
   ]
  },
  {
   "title": "Dagbag Size",
   "type": "stat",
   "description": "Amount of DAGs the scheduler is processing",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(airflow_dagbag_size{namespace=~\"$deployment\"})",
     "legendFormat": "Schedulers"
    }
   ]
  },
  {
   "title": "Scheduler Heartrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "expr": "max(irate(airflow_scheduler_heartbeat_total{namespace=\"$deployment\"}[5m]) * 60)",
     "legendFormat": "Heartrate"
    },
    { "expr": "12", "legendFormat": "Target" }
   ]
  },
  {
   "title": "Scheduler CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container=\"scheduler\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"core\", container=\"scheduler\", namespace=\"$deployment\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Scheduler Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$deployment\", container=\"scheduler\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"byte\", container=\"scheduler\", namespace=\"$deployment\", resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Pool Status : $deployment",
   "type": "bargauge",
   "description": "Scheduler Pool Status",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "repeat": "deployment",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(airflow_pool_open_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "OPEN: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_queued_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "QUEUED: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_running_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "RUNNING: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_starving_tasks{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "STARVING: {{pool}}"
    }
   ]
  },
  {
   "title": "Pool Status Trend : $deployment",
   "type": "timeseries",
   "description": "Scheduler Pool Status",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(airflow_pool_open_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "OPEN: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_queued_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "QUEUED: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_running_slots{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "RUNNING: {{pool}}"
    },
    {
     "expr": "max(airflow_pool_starving_tasks{namespace=\"$deployment\"}) by (pool)",
     "legendFormat": "STARVING: {{pool}}"
    }
   ]
  },
  { "title": "API Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "API Server",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (container_memory_working_set_bytes{namespace=\"$deployment\", container=\"apiserver\"}) or on ()vector(0)",
     "legendFormat": "Schedulers"
    }
   ]
  },
  {
   "title": "API Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container=\"apiserver\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"apiserver\", namespace=\"$deployment\"}) * 100",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "API Server Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$deployment\", container=\"apiserver\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{namespace=\"$deployment\", container=\"apiserver\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Worker Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (container_memory_working_set_bytes{namespace=\"$deployment\", container=\"worker\"}) or on ()vector(0)",
     "legendFormat": "workers"
    }
   ]
  },
  {
   "title": "Worker CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container=\"worker\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"core\", container=\"worker\", namespace=\"$deployment\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_labels{namespace=\"$deployment\", label_kubernetes_pod_operator=\"True\"} * on (pod) group_left sum without (container, image) (rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container!=\"\", pod!=\"\", name=\"\"}[5m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_labels{namespace=\"$deployment\", label_kubernetes_executor=\"True\"} * on (pod) group_left sum without (container, image) (rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container!=\"\", pod!=\"\", name=\"\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$deployment\", container=\"worker\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"byte\", container=\"worker\", namespace=\"$deployment\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_labels{namespace=\"$deployment\", label_kubernetes_pod_operator=\"True\"} * on (pod) group_left sum without (container, image) (container_memory_working_set_bytes{namespace=\"$deployment\", container!=\"\", pod!=\"\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_labels{namespace=\"$deployment\", label_kubernetes_executor=\"True\"} * on (pod) group_left sum without (container, image) (container_memory_working_set_bytes{namespace=\"$deployment\", container!=\"\", pod!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage of Airflow Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (label_replace(kube_pod_container_resource_limits{resource=\"ephemeral_storage\", cluster_id=\"$cluster\", namespace=\"$deployment\", pod=~\".*worker.*\"}, \"queue\", \"$1\", \"pod\", \".*-.*-[0-9]{4}-worker-(.*)-.*-.*\")) by (queue)",
     "legendFormat": "\"{{ queue }}\" worker queue storage limit"
    },
    {
     "expr": "kubelet_stats_ephemeral_storage_pod_usage{cluster_id=\"$cluster\", pod_namespace=\"$deployment\", pod_name=~\".*worker.*\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Ephemeral Storage Usage of Airflow KE/KPOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (kube_pod_container_resource_limits{resource=\"ephemeral_storage\", cluster_id=\"$cluster\", namespace=\"$deployment\", pod!~\"^($deployment|sensor).*$\"}) by (pod)",
     "legendFormat": "{{ pod }} storage limit"
    },
    {
     "expr": "kubelet_stats_ephemeral_storage_pod_usage{cluster_id=\"$cluster\", pod_namespace=\"$deployment\", pod_name!~\"^($deployment|sensor).*$\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Triggerer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Triggerer Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (container_memory_working_set_bytes{namespace=\"$deployment\", container=\"triggerer\"}) or on ()vector(0)",
     "legendFormat": "workers"
    }
   ]
  },
  {
   "title": "Triggerer CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container=\"triggerer\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"core\", container=\"triggerer\", namespace=\"$deployment\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Triggerer Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$deployment\", container=\"triggerer\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{unit=\"byte\", container=\"triggerer\", namespace=\"$deployment\", resource=\"memory\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Running Triggers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "airflow_triggers_running{namespace=\"$deployment\"}",
     "legendFormat": "running"
    },
    {
     "expr": "airflow_triggers_failed{namespace=\"$deployment\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "airflow_triggers_succeeded{namespace=\"$deployment\"}",
     "legendFormat": "succeeded"
    }
   ]
  },
  { "title": "PGBouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "PGBouncer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (container_memory_working_set_bytes{namespace=\"$deployment\", container=\"pgbouncer\"}) or on ()vector(0)",
     "legendFormat": "workers"
    }
   ]
  },
  {
   "title": "PGBouncer CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$deployment\", container=\"pgbouncer\"}[5m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"pgbouncer\", namespace=\"$deployment\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "PGBouncer Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$deployment\", container=\"pgbouncer\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{container=\"pgbouncer\", namespace=\"$deployment\"})",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}